### ISSUE TITLE
Blender color values different in Unity

### ISSUE THREAD

**Issue by IKStreamIvo** [Koxel/Koxel#6]
For some reason the colors we picked in Blender are different in Unity (imported via JSON).

**Comment by NaamloosDT** [comment]
Are you parsing them correctly?

**Comment by IKStreamIvo** [comment]
Of course :P

**Comment by Crauzer** [comment]
Is the format BGRA or RGBA ?

**Comment by IKStreamIvo** [comment]
This works, thanks :D
